added additional params argument
sportlobster/supervisor-newrelic pull request #7
Opened 2022-10-06 11:14 UTC by bgruszka

In Displate we want to pass additional params to NewRelic (like env for example). In order to do that I added param which can be set while launching supervisor_newrelic_status

2022-10-06 13:46 UTC, araines requested changes
If you could please document how to provide the additional params in the README as well, then I'll be happy to merge this (around line 33 is what I'm thinking)

2022-10-10 09:18 UTC, bgruszka commented
@araines added some docs :) can you take a look?

2022-10-10 09:25 UTC, araines approved these changes

2022-10-10 09:25 UTC, merged

2022-10-10 09:25 UTC, araines commented
Many thanks!